name = "stengttunnel-no"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./out"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]
